global:
  imagePullSecrets:
  - application-collection
cluster:
  enabled: true
standalone:
  persistence:
    persistentVolumeClaim:
      storageClass: longhorn-single-replica
etcd:
  replicaCount: 1
  persistence:
    storageClassName: longhorn-single-replica
minio:
  mode: distributed
  replicas: 3
  rootUser: "admin"
  rootPassword: "adminminio"
  persistence:
    storageClass: longhorn-single-replica
    size: 100Gi
  resources:
    requests:
      memory: 1024Mi
kafka:
  enabled: true
  name: kafka
  replicaCount: 3
  broker:
    enabled: true
  cluster:
    listeners:
      client:
        protocol: 'PLAINTEXT'
      controller:
        protocol: 'PLAINTEXT'
  persistence:
    enabled: true
    annotations: {}
    labels: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: "longhorn-xfs-single-replica"

