global:
  imagePullSecrets:
  - application-collection
  image:
    registry: dp.apps.rancher.io
    repository: containers/open-webui
    tag: 0.3.32
    pullPolicy: IfNotPresent
  ollamaUrls:
    - http://ollama.suse-ai.svc.cluster.local:11434
  persistence:
    enabled: true
    storageClass: local-path
ollama:
  enabled: false
pipelines:
  enabled: false
persistence:
  storageClass: local-path
ingress:
  enabled: true
  class: ""
  # annotations:
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true" ## Remove comments if using TLS and cert-manager to create certs for your host.
  host: suse-ai.example.com
  tls: false # Set to true if you have a domain.
extraEnvVars:
  - name: DEFAULT_MODELS
    value: "gemma:2b"
  - name: DEFAULT_USER_ROLE
    value: "user"
  - name: WEBUI_NAME
    value: "SUSE AI"
  - name: GLOBAL_LOG_LEVEL
    value: INFO
  - name: RAG_EMBEDDING_MODEL
    value: "sentence-transformers/all-MiniLM-L6-v2"
  - name: VECTOR_DB
    value: "milvus"
  - name: MILVUS_URI
    value: http://milvus.suse-ai.svc.cluster.local:19530
